// Song database with Spotify track IDs
const SONGS_DATABASE = [
    // 1950s
    { title: "Johnny B. Goode", artist: "Chuck Berry", year: 1958, spotifyId: "4OqHfSB4UN2THL2cYAFN3L" },
    { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957, spotifyId: "5VnDkUNyX6u5Sk0yZiP8XB" },
    { title: "Hound Dog", artist: "Elvis Presley", year: 1956, spotifyId: "64Ny7djQ6rNJspquof2KoX" },
    { title: "Rock Around the Clock", artist: "Bill Haley & His Comets", year: 1954, spotifyId: "7hLOIb9E7VKmsVelNq6YZK" },
    { title: "Great Balls of Fire", artist: "Jerry Lee Lewis", year: 1957, spotifyId: "7xe3EQCvXnx6Q0zs41Y65n" },
    { title: "La Bamba", artist: "Ritchie Valens", year: 1958, spotifyId: "2aEeghgUcnu75tzcolFMfs" },
    { title: "Tutti Frutti", artist: "Little Richard", year: 1955, spotifyId: "17nFSc5cJ3AHKt7qsGFtsz" },
    { title: "Peggy Sue", artist: "Buddy Holly", year: 1957, spotifyId: "5I3m1pOJoA8fgEMH8SWCJx" },

    // 1960s
    { title: "Hey Jude", artist: "The Beatles", year: 1968, spotifyId: "0aym2LBJBk9DAYuHHutrIl" },
    { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965, spotifyId: "0yOzLGO1rIw78ZZJerLdBw" },
    { title: "Respect", artist: "Aretha Franklin", year: 1967, spotifyId: "7s25THrKz86DM225dOYwnr" },
    { title: "What a Wonderful World", artist: "Louis Armstrong", year: 1967, spotifyId: "29U7stRjqHU6rMiS8BfaI9" },
    { title: "Stand By Me", artist: "Ben E. King", year: 1961, spotifyId: "3SdTKo2uVsxFblQjpScoHy" },
    { title: "My Girl", artist: "The Temptations", year: 1964, spotifyId: "745H5CctFr12Mo7cqa1BMH" },
    { title: "I Got You (I Feel Good)", artist: "James Brown", year: 1965, spotifyId: "5haXbSJqjjM0TCJ5XkfEaC" },
    { title: "Good Vibrations", artist: "The Beach Boys", year: 1966, spotifyId: "5t9KYe0Fhd5cW6UYT4qP8f" },
    { title: "Paint It Black", artist: "The Rolling Stones", year: 1966, spotifyId: "63T7DJ1AFDD6Bn8VzG6JE8" },
    { title: "Fortunate Son", artist: "Creedence Clearwater Revival", year: 1969, spotifyId: "4BP3uh0hFLFRb5cjsgLqDh" },
    { title: "Come Together", artist: "The Beatles", year: 1969, spotifyId: "2EqlS6tkEnglzr7tkKAAYD" },
    { title: "Ring of Fire", artist: "Johnny Cash", year: 1963, spotifyId: "6YffUZJ2R06kyxyK6onezL" },
    { title: "A Change Is Gonna Come", artist: "Sam Cooke", year: 1964, spotifyId: "5CjXQuNWHrLiZGbeF1sZhq" },

    // 1970s
    { title: "Bohemian Rhapsody", artist: "Queen", year: 1975, spotifyId: "7tFiyTwD0nx5a1eklYtX2J" },
    { title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971, spotifyId: "5CQ30WqJwcep0pYcV4AMNc" },
    { title: "Hotel California", artist: "Eagles", year: 1977, spotifyId: "40riOy7x9W7GXjyGp4pjAv" },
    { title: "Imagine", artist: "John Lennon", year: 1971, spotifyId: "7pKfPomDEeI4TPT6EOYjn9" },
    { title: "Stayin' Alive", artist: "Bee Gees", year: 1977, spotifyId: "4P0pKVi0gI56WszJ5clpaI" },
    { title: "Dancing Queen", artist: "ABBA", year: 1976, spotifyId: "0GjEhVFGZW8afUYGChu3Rr" },
    { title: "Waterloo", artist: "ABBA", year: 1974, spotifyId: "3Dy4REq8O09IlgiwuHQ3sk" },
    { title: "No Woman, No Cry", artist: "Bob Marley", year: 1975, spotifyId: "18rF49Lgmn0z3JEEzmgQ9C" },
    { title: "We Will Rock You", artist: "Queen", year: 1977, spotifyId: "54flyrjcdnQdco7300avMJ" },
    { title: "YMCA", artist: "Village People", year: 1978, spotifyId: "5kLQVVKkJXjTICBjGRTHcr" },
    { title: "I Will Survive", artist: "Gloria Gaynor", year: 1978, spotifyId: "5r3U0Z4jWEWEW2l0fdFxpZ" },
    { title: "Dreams", artist: "Fleetwood Mac", year: 1977, spotifyId: "0ofHAoxe9vBkTCp2UQIavz" },
    { title: "Go Your Own Way", artist: "Fleetwood Mac", year: 1977, spotifyId: "4lhFBcrzqfMKoP3Z8E3HIx" },
    { title: "Superstition", artist: "Stevie Wonder", year: 1972, spotifyId: "4xjgiJ19s0pfRjDgoQFznR" },
    { title: "Heart of Gold", artist: "Neil Young", year: 1972, spotifyId: "1Q1b8eVkUPGlpSArl8JAVw" },
    { title: "Heroes", artist: "David Bowie", year: 1977, spotifyId: "7Jh1bpe76CNTCgdgAdBw4Z" },
    { title: "Born to Run", artist: "Bruce Springsteen", year: 1975, spotifyId: "6hTcuIQa0sxrrByu9wTD7s" },
    { title: "September", artist: "Earth, Wind & Fire", year: 1978, spotifyId: "4f2GB5ZC7vOUYPAg69N2Xw" },

    // 1980s
    { title: "Billie Jean", artist: "Michael Jackson", year: 1983, spotifyId: "7J1uxwnxfQLu4APicE5Rnj" },
    { title: "Beat It", artist: "Michael Jackson", year: 1983, spotifyId: "1OOtq8tRnDM8kG2gqUPjAj" },
    { title: "Like a Prayer", artist: "Madonna", year: 1989, spotifyId: "1z3ugFmUKoCzGsI6jdY4Ci" },
    { title: "Purple Rain", artist: "Prince", year: 1984, spotifyId: "1uvyZBs4IZYRebHIB1747m" },
    { title: "Take on Me", artist: "a-ha", year: 1985, spotifyId: "2WfaOiMkCvy7F5fcp2zZ8L" },
    { title: "Sweet Dreams", artist: "Eurythmics", year: 1983, spotifyId: "1TfqLAPs4K3s2rJMoCokcS" },
    { title: "Every Breath You Take", artist: "The Police", year: 1983, spotifyId: "1JSTJqkT5qHq8MDJnJbRE1" },
    { title: "Under Pressure", artist: "Queen & David Bowie", year: 1981, spotifyId: "4FYeIka527pqJV5Jm5EXai" },
    { title: "Don't Stop Believin'", artist: "Journey", year: 1981, spotifyId: "4bHsxqR3GMrXTxEPLuK5ue" },
    { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986, spotifyId: "1K95m0tusqzkVum2PmzeIk" },
    { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1988, spotifyId: "7o2CTH4ctstm8TNelqjb51" },
    { title: "Africa", artist: "Toto", year: 1982, spotifyId: "2374M0fQpWi3dLnB54qaLX" },
    { title: "Eye of the Tiger", artist: "Survivor", year: 1982, spotifyId: "2HBwKhdashul8IjmhPMeCH" },
    { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987, spotifyId: "4PTG3Z6ehGkBFwjybzWkR8" },
    { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: 1987, spotifyId: "2tUBqZG2AbRi7Q0BIrVrEj" },
    { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983, spotifyId: "3MlVJGSJQ3GBBnlRnEKz0B" },
    { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", year: 1983, spotifyId: "7wuJGgpTNzbUyn26IOY6rj" },
    { title: "Jump", artist: "Van Halen", year: 1984, spotifyId: "37ZJ0p5Jm13UiJoLMm0X9N" },
    { title: "Blue Monday", artist: "New Order", year: 1983, spotifyId: "7INHYSeusaFlyasZv0mvmp" },

    // 1990s
    { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991, spotifyId: "5ghIJDpPoe3CfHMGu71E6T" },
    { title: "Wonderwall", artist: "Oasis", year: 1995, spotifyId: "1qPbGZqppFwLwcBC1JQ6Vr" },
    { title: "Creep", artist: "Radiohead", year: 1993, spotifyId: "70LcF31zb1H0PyJoS1Sx1r" },
    { title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1992, spotifyId: "3d9DChrdc6BOeFsbrZ3Is0" },
    { title: "Nothing Else Matters", artist: "Metallica", year: 1992, spotifyId: "0fF3wALCVHZHzaH6FEmJMN" },
    { title: "Zombie", artist: "The Cranberries", year: 1994, spotifyId: "7yCWMlSDETCFppOXZflm1e" },
    { title: "...Baby One More Time", artist: "Britney Spears", year: 1999, spotifyId: "3MjUtNVVq3C8Fn0MP3zhXa" },
    { title: "Wannabe", artist: "Spice Girls", year: 1996, spotifyId: "1Je1IMUlBXcx1Fz0WE7oeT" },
    { title: "My Heart Will Go On", artist: "Celine Dion", year: 1997, spotifyId: "33LC84JgLvK2KuW43MfaNq" },
    { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992, spotifyId: "4eHbdreAnSOrDDsFfc4Fpm" },
    { title: "Gangsta's Paradise", artist: "Coolio", year: 1995, spotifyId: "1DIXPcTDzTj8ZMHt3PDt8p" },
    { title: "Barbie Girl", artist: "Aqua", year: 1997, spotifyId: "2LiGKnCqrJmauRFI6fBotf" },
    { title: "Believe", artist: "Cher", year: 1998, spotifyId: "2goLsvvODILDzeeiT4dAoR" },
    { title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997, spotifyId: "57iDDD9N4BmXD3sQIGNlxm" },
    { title: "Torn", artist: "Natalie Imbruglia", year: 1997, spotifyId: "0KDaN0HL3TcJVTbXlQCEsS" },
    { title: "Losing My Religion", artist: "R.E.M.", year: 1991, spotifyId: "31AOj9sFz2gM0O3hMARRBx" },
    { title: "No Diggity", artist: "Blackstreet", year: 1996, spotifyId: "0F7iKgb1qGKMAmmB5JfpXa" },
    { title: "Killing Me Softly", artist: "Fugees", year: 1996, spotifyId: "0Q0IVlqMV64kNLlwjPj0Hl" },
    { title: "MMMBop", artist: "Hanson", year: 1997, spotifyId: "0lnxrQAd9ZxbhBBe7d8FO8" },
    { title: "I Want It That Way", artist: "Backstreet Boys", year: 1999, spotifyId: "47BBI51FKFwOMlIiX6m8ya" },
    { title: "Waterfalls", artist: "TLC", year: 1995, spotifyId: "6qspW4YKycviDFjHBOaqUY" },
    { title: "California Love", artist: "2Pac", year: 1995, spotifyId: "61bLhALkT5ibYHRZFNfyxZ" },

    // 2000s
    { title: "Crazy in Love", artist: "Beyonce", year: 2003, spotifyId: "5IVuqXILoxVWvWEPm82Jxr" },
    { title: "Lose Yourself", artist: "Eminem", year: 2002, spotifyId: "5Z01UMMf7V1o0MzF86s6WJ" },
    { title: "Hey Ya!", artist: "OutKast", year: 2003, spotifyId: "2PpruBYCo4H7WOBJ7Q2EwM" },
    { title: "Mr. Brightside", artist: "The Killers", year: 2004, spotifyId: "003vvx7Niy0yvhvHt4a68B" },
    { title: "Seven Nation Army", artist: "The White Stripes", year: 2003, spotifyId: "7i6r9KotUPQg3WDBATA5Nk" },
    { title: "Toxic", artist: "Britney Spears", year: 2004, spotifyId: "6I9VzXrHxO9rA9A5euc8Ak" },
    { title: "Poker Face", artist: "Lady Gaga", year: 2008, spotifyId: "1QV6tiMFM6fSOKOGLMHYYg" },
    { title: "Umbrella", artist: "Rihanna", year: 2007, spotifyId: "2VcMXJYfEaYnq3XiUEULFM" },
    { title: "Hips Don't Lie", artist: "Shakira", year: 2006, spotifyId: "3ZFTkvIE7kyPt6Nu3PEa7V" },
    { title: "Fix You", artist: "Coldplay", year: 2005, spotifyId: "7LVHVU3tWfcxj5aiPFEW4Q" },
    { title: "Viva la Vida", artist: "Coldplay", year: 2008, spotifyId: "1mea3bSkSGXuIRvnydlB5b" },
    { title: "In the End", artist: "Linkin Park", year: 2001, spotifyId: "60a0Rd6pjrkxjPbaKzXjfq" },
    { title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004, spotifyId: "7lQ8MOhq6IN2w8EYcFNSUk" },
    { title: "Rehab", artist: "Amy Winehouse", year: 2007, spotifyId: "6xMrq5aSpIhhKQBNFVaqBn" },
    { title: "Crazy", artist: "Gnarls Barkley", year: 2006, spotifyId: "5B8Xjq9Dv0RX2oqUNkYmfH" },
    { title: "Feel Good Inc.", artist: "Gorillaz", year: 2005, spotifyId: "0d28khcov6AiegSCpG5TuT" },
    { title: "Yeah!", artist: "Usher", year: 2004, spotifyId: "1Cwml2JIvDNf70AjN4QGYP" },
    { title: "Love Story", artist: "Taylor Swift", year: 2008, spotifyId: "1vrd6UOGamcKNGnSHJQlSt" },
    { title: "Maps", artist: "Yeah Yeah Yeahs", year: 2003, spotifyId: "0hDQV9X1Da5JrwhK8gu86p" },
    { title: "Clocks", artist: "Coldplay", year: 2002, spotifyId: "0BCPKOYdS2jbQ8iyB56Zns" },
    { title: "Paper Planes", artist: "M.I.A.", year: 2007, spotifyId: "1ixbwbeBi5ufN4noUKmW5a" },
    { title: "SOS", artist: "Rihanna", year: 2006, spotifyId: "6fG7EM3KWxiBSeyL5m6Ibp" },

    // 2010s
    { title: "Rolling in the Deep", artist: "Adele", year: 2011, spotifyId: "6IAZHEBUIGJ6NJKxxOBIEr" },
    { title: "Someone Like You", artist: "Adele", year: 2011, spotifyId: "3bNv3VNVlLR9veFKi3VDXL" },
    { title: "Hello", artist: "Adele", year: 2015, spotifyId: "4sPmO7WMQUAf45kwMOtONw" },
    { title: "Somebody That I Used to Know", artist: "Gotye", year: 2011, spotifyId: "1qDrWA6lyx8cLECdZE7TV7" },
    { title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2012, spotifyId: "20I6sIOMTCkB6w7ryavxtO" },
    { title: "Gangnam Style", artist: "PSY", year: 2012, spotifyId: "03UrZgTINDqvnUMbbIMhql" },
    { title: "Get Lucky", artist: "Daft Punk", year: 2013, spotifyId: "69kOkLUCkxIZYexIgSG8rq" },
    { title: "Royals", artist: "Lorde", year: 2013, spotifyId: "2dLLR6qlu5UJ5gk0dKz0h3" },
    { title: "Happy", artist: "Pharrell Williams", year: 2013, spotifyId: "04c0sgiXUEBi0EtCFHZgof" },
    { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", year: 2014, spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014, spotifyId: "34gCuhDGsG4bRPIf9bb02f" },
    { title: "Shape of You", artist: "Ed Sheeran", year: 2017, spotifyId: "0FE9t6xYkqWXU2ahLh6D8X" },
    { title: "Blinding Lights", artist: "The Weeknd", year: 2020, spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    { title: "Starboy", artist: "The Weeknd", year: 2016, spotifyId: "7MXVkFLYF7YBqeePM7SPCo" },
    { title: "Despacito", artist: "Luis Fonsi", year: 2017, spotifyId: "6habFhsOp2NvshLv26DqMb" },
    { title: "Closer", artist: "The Chainsmokers", year: 2016, spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    { title: "Take Me to Church", artist: "Hozier", year: 2013, spotifyId: "1CS7Sd1u5tL5yVCDoecko6" },
    { title: "Sorry", artist: "Justin Bieber", year: 2015, spotifyId: "09CtPGIpYB4BrO8qb1RGsF" },
    { title: "Hotline Bling", artist: "Drake", year: 2015, spotifyId: "0SF6K3jJbS5kPBULBkNPsA" },
    { title: "God's Plan", artist: "Drake", year: 2018, spotifyId: "6DCZcSspjsKoFjzjrWoCdn" },
    { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: 2018, spotifyId: "2VxeLyX666F8uXCJ0dZF8B" },
    { title: "Old Town Road", artist: "Lil Nas X", year: 2019, spotifyId: "2YpeDb67231RjR0MgVLzsG" },
    { title: "bad guy", artist: "Billie Eilish", year: 2019, spotifyId: "2Fxmhks0bxGSBdJ92vM42m" },
    { title: "Sunflower", artist: "Post Malone & Swae Lee", year: 2018, spotifyId: "3KkXRkHbMCARz0aVfEt68P" },
    { title: "Thank U, Next", artist: "Ariana Grande", year: 2019, spotifyId: "2rPE9A1vEgShuZxxzR2tZH" },
    { title: "Dance Monkey", artist: "Tones and I", year: 2019, spotifyId: "2XU0oxnq2qxCpomAAuJY8K" },
    { title: "Don't Start Now", artist: "Dua Lipa", year: 2019, spotifyId: "3PfIrDoz19wz7qK7tYeu62" },
    { title: "Radioactive", artist: "Imagine Dragons", year: 2012, spotifyId: "69yfbpvmkIaB3KmnV3vkME" },
    { title: "Shake It Off", artist: "Taylor Swift", year: 2014, spotifyId: "0cqRj7pUJDkTCEsJkx8snX" },
    { title: "Blank Space", artist: "Taylor Swift", year: 2014, spotifyId: "1p80LdxRV74UKvRs7RCas0" },
    { title: "Chandelier", artist: "Sia", year: 2014, spotifyId: "2rCbP4V3VWn4k8yGHfNEh0" },
    { title: "Pompeii", artist: "Bastille", year: 2013, spotifyId: "4VnDmjYCZkyeMMY10y2PFe" },
    { title: "Locked Out of Heaven", artist: "Bruno Mars", year: 2012, spotifyId: "3w3y8KPTfNeOKPiqUTakBh" },
    { title: "Faded", artist: "Alan Walker", year: 2015, spotifyId: "7gHs73wELdeycvS48JfIos" },
    { title: "Stressed Out", artist: "Twenty One Pilots", year: 2015, spotifyId: "3CRDbSIZ4r5MsZ0YwxuEkn" },
    { title: "Wrecking Ball", artist: "Miley Cyrus", year: 2013, spotifyId: "7FGq80cy4nHJXSgUGPMItg" },
    { title: "Counting Stars", artist: "OneRepublic", year: 2013, spotifyId: "2tpWsVSagGXKVYdP1XtBwL" },
    { title: "Let Her Go", artist: "Passenger", year: 2012, spotifyId: "3zqFLMDBMCWp5bnJUkaMjS" },
    { title: "The Fox (What Does the Fox Say?)", artist: "Ylvis", year: 2013, spotifyId: "4rsJPWMRyT7JNnGw7V8K0w" },

    // 2020s
    { title: "Watermelon Sugar", artist: "Harry Styles", year: 2020, spotifyId: "6UelLqGlWMcVH1E5c4H7lY" },
    { title: "As It Was", artist: "Harry Styles", year: 2022, spotifyId: "4LRPiXqCikLlN15c3yImP7" },
    { title: "good 4 u", artist: "Olivia Rodrigo", year: 2021, spotifyId: "4ZtFanR9U6ndgddUvNcjcG" },
    { title: "Drivers License", artist: "Olivia Rodrigo", year: 2021, spotifyId: "1jo8sE5tvfGtS56sCHXuuP" },
    { title: "Montero", artist: "Lil Nas X", year: 2021, spotifyId: "67BtfxlNbhBKdraz4163gd" },
    { title: "Save Your Tears", artist: "The Weeknd", year: 2020, spotifyId: "5QO79kh1waicV47BqGRL3g" },
    { title: "Heat Waves", artist: "Glass Animals", year: 2020, spotifyId: "02MWAaffLxlfxAUY7c5dvx" },
    { title: "Easy On Me", artist: "Adele", year: 2021, spotifyId: "46s57QULU02VSKqpFFMgOE" },
    { title: "Anti-Hero", artist: "Taylor Swift", year: 2022, spotifyId: "0V3wPSX9ygBnCm8psDIegu" },
    { title: "Flowers", artist: "Miley Cyrus", year: 2023, spotifyId: "7DSAEUvxU8FajXtRloy8M0" },
    { title: "About Damn Time", artist: "Lizzo", year: 2022, spotifyId: "1PckUlxKqWQs3RlWXVBLw3" },
    { title: "Stay", artist: "The Kid LAROI & Justin Bieber", year: 2021, spotifyId: "5PjdY0CKGZdEuoNab3yDmX" },
    { title: "Levitating", artist: "Dua Lipa", year: 2020, spotifyId: "463CkQjx2Zk1yXoBuierM9" },
    { title: "Peaches", artist: "Justin Bieber", year: 2021, spotifyId: "4iJyoBOLtHEmRTsufTCjWp" },
    { title: "Dynamite", artist: "BTS", year: 2020, spotifyId: "5QDLhrAOJJdNAmCTJ8xMyW" },
    { title: "Beggin'", artist: "Maneskin", year: 2021, spotifyId: "3Wrjm47oTz2sjIgck11l5e" },
    { title: "Vampire", artist: "Olivia Rodrigo", year: 2023, spotifyId: "1kuGVB7EU95pJObxwvfwKS" },
    { title: "Kill Bill", artist: "SZA", year: 2022, spotifyId: "1Qrg8KqiBpW07V7PNxwwwL" },
    { title: "Cruel Summer", artist: "Taylor Swift", year: 2019, spotifyId: "1BxfuPKGuaTgP7aM0Bbdwr" },
    { title: "Espresso", artist: "Sabrina Carpenter", year: 2024, spotifyId: "2qSkIjg1o9h3YT9RAgYN75" },
    { title: "Snooze", artist: "SZA", year: 2022, spotifyId: "5gHx5zPHcs5yYQC2jKFnVZ" },
    { title: "Unholy", artist: "Sam Smith & Kim Petras", year: 2022, spotifyId: "3nqQXoyQOWXiESFLlDF1hG" },
    { title: "Calm Down", artist: "Rema & Selena Gomez", year: 2022, spotifyId: "0WtM2NBVQNNJLh6scP13H8" },
    { title: "Paint The Town Red", artist: "Doja Cat", year: 2023, spotifyId: "2IGMVunIBsBLtEQyoI1Mu7" },
    { title: "Fortnight", artist: "Taylor Swift ft. Post Malone", year: 2024, spotifyId: "6GrvlxquXWumwyNeZb1oZz" },
    { title: "Die With A Smile", artist: "Lady Gaga & Bruno Mars", year: 2024, spotifyId: "2plbrEY59IikOBgBGLjaoe" },
    { title: "Birds of a Feather", artist: "Billie Eilish", year: 2024, spotifyId: "6dOtVTDdiauQNBQEDOtlAB" },
    { title: "Greedy", artist: "Tate McRae", year: 2023, spotifyId: "3rUGC1vUpkDG9CZFHMur1t" },
    { title: "Lovin On Me", artist: "Jack Harlow", year: 2023, spotifyId: "4xhsWYTOGcal8zt0J161CU" },
];

// Fisher-Yates shuffle
function shuffleArray(arr) {
    const shuffled = [...arr];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}
