// Database of well-known hit songs with title, artist, and release year
const SONGS_DATABASE = [
    // 1950s
    { title: "Johnny B. Goode", artist: "Chuck Berry", year: 1958 },
    { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957 },
    { title: "Hound Dog", artist: "Elvis Presley", year: 1956 },
    { title: "Rock Around the Clock", artist: "Bill Haley & His Comets", year: 1955 },
    { title: "Great Balls of Fire", artist: "Jerry Lee Lewis", year: 1957 },
    { title: "Tutti Frutti", artist: "Little Richard", year: 1955 },
    { title: "La Bamba", artist: "Ritchie Valens", year: 1958 },

    // 1960s
    { title: "I Want to Hold Your Hand", artist: "The Beatles", year: 1963 },
    { title: "Hey Jude", artist: "The Beatles", year: 1968 },
    { title: "Let It Be", artist: "The Beatles", year: 1970 },
    { title: "Yesterday", artist: "The Beatles", year: 1965 },
    { title: "Come Together", artist: "The Beatles", year: 1969 },
    { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965 },
    { title: "Paint It Black", artist: "The Rolling Stones", year: 1966 },
    { title: "Respect", artist: "Aretha Franklin", year: 1967 },
    { title: "My Girl", artist: "The Temptations", year: 1964 },
    { title: "What a Wonderful World", artist: "Louis Armstrong", year: 1967 },
    { title: "The Sound of Silence", artist: "Simon & Garfunkel", year: 1964 },
    { title: "Stand By Me", artist: "Ben E. King", year: 1961 },
    { title: "Fortunate Son", artist: "Creedence Clearwater Revival", year: 1969 },
    { title: "Purple Haze", artist: "Jimi Hendrix", year: 1967 },
    { title: "Good Vibrations", artist: "The Beach Boys", year: 1966 },
    { title: "River Deep - Mountain High", artist: "Ike & Tina Turner", year: 1966 },
    { title: "Piece of My Heart", artist: "Janis Joplin", year: 1968 },

    // 1970s
    { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
    { title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
    { title: "Hotel California", artist: "Eagles", year: 1977 },
    { title: "Imagine", artist: "John Lennon", year: 1971 },
    { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
    { title: "Dancing Queen", artist: "ABBA", year: 1976 },
    { title: "Waterloo", artist: "ABBA", year: 1974 },
    { title: "SOS", artist: "ABBA", year: 1975 },
    { title: "Fernando", artist: "ABBA", year: 1976 },
    { title: "Superstition", artist: "Stevie Wonder", year: 1972 },
    { title: "I Will Survive", artist: "Gloria Gaynor", year: 1978 },
    { title: "Blitzkrieg Bop", artist: "Ramones", year: 1976 },
    { title: "Go Your Own Way", artist: "Fleetwood Mac", year: 1977 },
    { title: "Dreams", artist: "Fleetwood Mac", year: 1977 },
    { title: "Wish You Were Here", artist: "Pink Floyd", year: 1975 },
    { title: "Another Brick in the Wall", artist: "Pink Floyd", year: 1979 },
    { title: "Born to Run", artist: "Bruce Springsteen", year: 1975 },
    { title: "Heart of Glass", artist: "Blondie", year: 1979 },
    { title: "Rapper's Delight", artist: "The Sugarhill Gang", year: 1979 },
    { title: "YMCA", artist: "Village People", year: 1978 },
    { title: "We Will Rock You", artist: "Queen", year: 1977 },
    { title: "Night Fever", artist: "Bee Gees", year: 1977 },
    { title: "No Woman, No Cry", artist: "Bob Marley", year: 1975 },
    { title: "Three Little Birds", artist: "Bob Marley", year: 1977 },

    // 1980s
    { title: "Billie Jean", artist: "Michael Jackson", year: 1983 },
    { title: "Beat It", artist: "Michael Jackson", year: 1983 },
    { title: "Thriller", artist: "Michael Jackson", year: 1984 },
    { title: "Like a Virgin", artist: "Madonna", year: 1984 },
    { title: "Material Girl", artist: "Madonna", year: 1985 },
    { title: "Like a Prayer", artist: "Madonna", year: 1989 },
    { title: "Purple Rain", artist: "Prince", year: 1984 },
    { title: "When Doves Cry", artist: "Prince", year: 1984 },
    { title: "Take on Me", artist: "a-ha", year: 1985 },
    { title: "The Sun Always Shines on T.V.", artist: "a-ha", year: 1985 },
    { title: "Sweet Dreams", artist: "Eurythmics", year: 1983 },
    { title: "Every Breath You Take", artist: "The Police", year: 1983 },
    { title: "Under Pressure", artist: "Queen & David Bowie", year: 1981 },
    { title: "Blue Monday", artist: "New Order", year: 1983 },
    { title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
    { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
    { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1988 },
    { title: "Welcome to the Jungle", artist: "Guns N' Roses", year: 1987 },
    { title: "With or Without You", artist: "U2", year: 1987 },
    { title: "I Still Haven't Found What I'm Looking For", artist: "U2", year: 1987 },
    { title: "Africa", artist: "Toto", year: 1982 },
    { title: "Eye of the Tiger", artist: "Survivor", year: 1982 },
    { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
    { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", year: 1983 },
    { title: "Everybody Wants to Rule the World", artist: "Tears for Fears", year: 1985 },
    { title: "Walk Like an Egyptian", artist: "The Bangles", year: 1986 },
    { title: "Pour Some Sugar on Me", artist: "Def Leppard", year: 1987 },
    { title: "Jump", artist: "Van Halen", year: 1984 },
    { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
    { title: "Faith", artist: "George Michael", year: 1987 },
    { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: 1987 },
    { title: "Enjoy the Silence", artist: "Depeche Mode", year: 1990 },
    { title: "Personal Jesus", artist: "Depeche Mode", year: 1989 },

    // 1990s
    { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
    { title: "Wonderwall", artist: "Oasis", year: 1995 },
    { title: "Don't Look Back in Anger", artist: "Oasis", year: 1996 },
    { title: "Creep", artist: "Radiohead", year: 1993 },
    { title: "Karma Police", artist: "Radiohead", year: 1997 },
    { title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
    { title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1992 },
    { title: "Californication", artist: "Red Hot Chili Peppers", year: 1999 },
    { title: "Nothing Else Matters", artist: "Metallica", year: 1992 },
    { title: "Enter Sandman", artist: "Metallica", year: 1991 },
    { title: "Zombie", artist: "The Cranberries", year: 1994 },
    { title: "No Diggity", artist: "Blackstreet", year: 1996 },
    { title: "...Baby One More Time", artist: "Britney Spears", year: 1999 },
    { title: "Wannabe", artist: "Spice Girls", year: 1996 },
    { title: "MMMBop", artist: "Hanson", year: 1997 },
    { title: "Iris", artist: "Goo Goo Dolls", year: 1998 },
    { title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997 },
    { title: "My Heart Will Go On", artist: "Celine Dion", year: 1997 },
    { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
    { title: "No Scrubs", artist: "TLC", year: 1999 },
    { title: "Waterfalls", artist: "TLC", year: 1995 },
    { title: "Gangsta's Paradise", artist: "Coolio", year: 1995 },
    { title: "California Love", artist: "2Pac", year: 1996 },
    { title: "Juicy", artist: "The Notorious B.I.G.", year: 1994 },
    { title: "Nuthin' but a 'G' Thang", artist: "Dr. Dre", year: 1992 },
    { title: "Jump Around", artist: "House of Pain", year: 1992 },
    { title: "Torn", artist: "Natalie Imbruglia", year: 1997 },
    { title: "Believe", artist: "Cher", year: 1998 },
    { title: "Macarena", artist: "Los Del Rio", year: 1996 },
    { title: "Barbie Girl", artist: "Aqua", year: 1997 },
    { title: "Blue (Da Ba Dee)", artist: "Eiffel 65", year: 1999 },
    { title: "Kiss from a Rose", artist: "Seal", year: 1995 },

    // 2000s
    { title: "Crazy in Love", artist: "Beyonce", year: 2003 },
    { title: "Single Ladies", artist: "Beyonce", year: 2008 },
    { title: "In Da Club", artist: "50 Cent", year: 2003 },
    { title: "Lose Yourself", artist: "Eminem", year: 2002 },
    { title: "Stan", artist: "Eminem", year: 2000 },
    { title: "Hey Ya!", artist: "OutKast", year: 2003 },
    { title: "Mr. Brightside", artist: "The Killers", year: 2004 },
    { title: "Seven Nation Army", artist: "The White Stripes", year: 2003 },
    { title: "Clocks", artist: "Coldplay", year: 2002 },
    { title: "The Scientist", artist: "Coldplay", year: 2002 },
    { title: "Fix You", artist: "Coldplay", year: 2005 },
    { title: "Toxic", artist: "Britney Spears", year: 2004 },
    { title: "Hips Don't Lie", artist: "Shakira", year: 2006 },
    { title: "Umbrella", artist: "Rihanna", year: 2007 },
    { title: "Poker Face", artist: "Lady Gaga", year: 2008 },
    { title: "Just Dance", artist: "Lady Gaga", year: 2008 },
    { title: "Gold Digger", artist: "Kanye West", year: 2005 },
    { title: "Stronger", artist: "Kanye West", year: 2007 },
    { title: "Harder Better Faster Stronger", artist: "Daft Punk", year: 2001 },
    { title: "Around the World", artist: "Daft Punk", year: 1997 },
    { title: "Feel Good Inc.", artist: "Gorillaz", year: 2005 },
    { title: "Crazy", artist: "Gnarls Barkley", year: 2006 },
    { title: "Rehab", artist: "Amy Winehouse", year: 2007 },
    { title: "Use Somebody", artist: "Kings of Leon", year: 2008 },
    { title: "Chasing Cars", artist: "Snow Patrol", year: 2006 },
    { title: "In the End", artist: "Linkin Park", year: 2001 },
    { title: "Numb", artist: "Linkin Park", year: 2003 },
    { title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004 },
    { title: "American Idiot", artist: "Green Day", year: 2004 },
    { title: "I Gotta Feeling", artist: "The Black Eyed Peas", year: 2009 },
    { title: "Viva la Vida", artist: "Coldplay", year: 2008 },
    { title: "Bleeding Love", artist: "Leona Lewis", year: 2007 },
    { title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004 },
    { title: "Yeah!", artist: "Usher", year: 2004 },
    { title: "SexyBack", artist: "Justin Timberlake", year: 2006 },
    { title: "Cry Me a River", artist: "Justin Timberlake", year: 2002 },

    // 2010s
    { title: "Rolling in the Deep", artist: "Adele", year: 2011 },
    { title: "Someone Like You", artist: "Adele", year: 2011 },
    { title: "Hello", artist: "Adele", year: 2015 },
    { title: "Somebody That I Used to Know", artist: "Gotye", year: 2011 },
    { title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2012 },
    { title: "Gangnam Style", artist: "PSY", year: 2012 },
    { title: "Get Lucky", artist: "Daft Punk", year: 2013 },
    { title: "Royals", artist: "Lorde", year: 2013 },
    { title: "Happy", artist: "Pharrell Williams", year: 2013 },
    { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", year: 2014 },
    { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014 },
    { title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
    { title: "Photograph", artist: "Ed Sheeran", year: 2014 },
    { title: "Blinding Lights", artist: "The Weeknd", year: 2020 },
    { title: "Starboy", artist: "The Weeknd", year: 2016 },
    { title: "Can't Feel My Face", artist: "The Weeknd", year: 2015 },
    { title: "Despacito", artist: "Luis Fonsi", year: 2017 },
    { title: "Havana", artist: "Camila Cabello", year: 2017 },
    { title: "Closer", artist: "The Chainsmokers", year: 2016 },
    { title: "Lean On", artist: "Major Lazer & DJ Snake", year: 2015 },
    { title: "Take Me to Church", artist: "Hozier", year: 2013 },
    { title: "Stitches", artist: "Shawn Mendes", year: 2015 },
    { title: "Sorry", artist: "Justin Bieber", year: 2015 },
    { title: "Love Yourself", artist: "Justin Bieber", year: 2015 },
    { title: "Hotline Bling", artist: "Drake", year: 2015 },
    { title: "God's Plan", artist: "Drake", year: 2018 },
    { title: "One Dance", artist: "Drake", year: 2016 },
    { title: "Formation", artist: "Beyonce", year: 2016 },
    { title: "Chandelier", artist: "Sia", year: 2014 },
    { title: "Cheap Thrills", artist: "Sia", year: 2016 },
    { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: 2018 },
    { title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
    { title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
    { title: "Sunflower", artist: "Post Malone & Swae Lee", year: 2018 },
    { title: "Rockstar", artist: "Post Malone", year: 2017 },
    { title: "Sicko Mode", artist: "Travis Scott", year: 2018 },
    { title: "This Is America", artist: "Childish Gambino", year: 2018 },
    { title: "Thank U, Next", artist: "Ariana Grande", year: 2019 },
    { title: "7 Rings", artist: "Ariana Grande", year: 2019 },
    { title: "Dance Monkey", artist: "Tones and I", year: 2019 },
    { title: "Senorita", artist: "Shawn Mendes & Camila Cabello", year: 2019 },
    { title: "Drivers License", artist: "Olivia Rodrigo", year: 2021 },
    { title: "Levitating", artist: "Dua Lipa", year: 2020 },
    { title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
    { title: "New Rules", artist: "Dua Lipa", year: 2017 },
    { title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
    { title: "Thunder", artist: "Imagine Dragons", year: 2017 },
    { title: "Pompeii", artist: "Bastille", year: 2013 },
    { title: "Riptide", artist: "Vance Joy", year: 2013 },
    { title: "Let Her Go", artist: "Passenger", year: 2012 },
    { title: "Stay With Me", artist: "Sam Smith", year: 2014 },
    { title: "Counting Stars", artist: "OneRepublic", year: 2013 },
    { title: "Locked Out of Heaven", artist: "Bruno Mars", year: 2012 },
    { title: "Just the Way You Are", artist: "Bruno Mars", year: 2010 },
    { title: "That's What I Like", artist: "Bruno Mars", year: 2017 },

    // 2020s
    { title: "Watermelon Sugar", artist: "Harry Styles", year: 2020 },
    { title: "As It Was", artist: "Harry Styles", year: 2022 },
    { title: "Peaches", artist: "Justin Bieber", year: 2021 },
    { title: "Stay", artist: "The Kid LAROI & Justin Bieber", year: 2021 },
    { title: "good 4 u", artist: "Olivia Rodrigo", year: 2021 },
    { title: "Montero", artist: "Lil Nas X", year: 2021 },
    { title: "Kiss Me More", artist: "Doja Cat", year: 2021 },
    { title: "Save Your Tears", artist: "The Weeknd", year: 2020 },
    { title: "Positions", artist: "Ariana Grande", year: 2020 },
    { title: "Dynamite", artist: "BTS", year: 2020 },
    { title: "Butter", artist: "BTS", year: 2021 },
    { title: "Heat Waves", artist: "Glass Animals", year: 2020 },
    { title: "Beggin'", artist: "Maneskin", year: 2021 },
    { title: "Easy On Me", artist: "Adele", year: 2021 },
    { title: "About Damn Time", artist: "Lizzo", year: 2022 },
    { title: "Anti-Hero", artist: "Taylor Swift", year: 2022 },
    { title: "Shake It Off", artist: "Taylor Swift", year: 2014 },
    { title: "Blank Space", artist: "Taylor Swift", year: 2014 },
    { title: "Love Story", artist: "Taylor Swift", year: 2008 },
    { title: "Bad Blood", artist: "Taylor Swift", year: 2015 },
    { title: "Cruel Summer", artist: "Taylor Swift", year: 2019 },
    { title: "Flowers", artist: "Miley Cyrus", year: 2023 },
    { title: "Wrecking Ball", artist: "Miley Cyrus", year: 2013 },
    { title: "Kill Bill", artist: "SZA", year: 2022 },
    { title: "Vampire", artist: "Olivia Rodrigo", year: 2023 },
    { title: "Calm Down", artist: "Rema & Selena Gomez", year: 2022 },
    { title: "Unholy", artist: "Sam Smith & Kim Petras", year: 2022 },
    { title: "Last Night", artist: "Morgan Wallen", year: 2023 },
    { title: "Escapism", artist: "RAYE", year: 2022 },
    { title: "Creepin'", artist: "Metro Boomin & The Weeknd", year: 2022 },

    // Norske hits
    { title: "The Fox (What Does the Fox Say?)", artist: "Ylvis", year: 2013 },
    { title: "Faded", artist: "Alan Walker", year: 2015 },
    { title: "I Took a Pill in Ibiza", artist: "Mike Posner", year: 2015 },
    { title: "Alone", artist: "Alan Walker", year: 2016 },
    { title: "On My Way", artist: "Alan Walker", year: 2019 },
    { title: "Ride", artist: "Twenty One Pilots", year: 2015 },
    { title: "Stressed Out", artist: "Twenty One Pilots", year: 2015 },
    { title: "Heathens", artist: "Twenty One Pilots", year: 2016 },
];

// Shuffle function using Fisher-Yates
function shuffleArray(arr) {
    const shuffled = [...arr];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}
